[View in Colaboratory](https://colab.research.google.com/github/shivamgoel1791/Other_projects/blob/master/Basic_Python_practice.ipynb)

In [0]:
import math
import statistics
import random
import numpy as np
import pandas as pd

**Is prime number**

In [0]:
def is_prime(N):
  i = 2
  while i < np.sqrt(N):
    if N/i == N//i:
      print ("N is divisible by",i,"& N is not prime")
      break
    else:
      i+=1
  else:
    print ("N is prime")

In [28]:
is_prime(1729)

N is divisible by 7 & N is not prime


**Save factors of any number in a list**

In [0]:
def fctrs_of_nmbr(N):
  i = 1
  l = []
  while i <= N:
    if N/i == N//i:
      l.append(i)
      i+=1
    else:
      i+=1
  else:
    print (l)

In [62]:
fctrs_of_nmbr(100)

[1, 2, 4, 5, 10, 20, 25, 50, 100]


**Zip in python**

In [0]:
A = [1, 2, 3]
B = [4, 5, 6]

In [0]:
C = [[x,y] for x,y in zip(A,B)]

In [77]:
C

[[1, 4], [2, 5], [3, 6]]

**Create a chess board pattern**

In [99]:
5%2 == 0

False

In [110]:
t = np.reshape(np.arange(1,65, dtype = int), (8,8), order = 'C')
t

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [0]:
for i in range(8):
  for j in range(8):
    if (i+j)%2 == 0:
      t[i,j] = 1
    else:
      t[i,j] = 0    

In [120]:
t

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**Checkerboard pattern using slicing though numpy**

In [0]:
p = np.zeros((8,8),dtype= int)

In [0]:
p[::2,::2] = 1

In [9]:
p

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
p[1::2, 1::2] = 1

In [11]:
p

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**Other tries**

In [1]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [8]:
np.random.rand(3,3)
np.zeros((3,3), dtype= int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
tl= np.linspace(1,10,3)

In [13]:
tl[tl>3]

array([ 5.5, 10. ])

In [14]:
tl

array([ 1. ,  5.5, 10. ])

In [15]:
tl.astype(int)

array([ 1,  5, 10])

In [16]:
tl

array([ 1. ,  5.5, 10. ])

In [0]:
k = {"a" : "hello", "b" : "World"}

In [25]:
len(k)

2

In [26]:
0

NameError: ignored